### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bahaedin** [meypod/al-azan#11]
**Hi bro** , first i want to thank you for this simple and beautiful app , i have two suggestions for you !

1. is to change the location of the Date according to the writing direction of the language

<details>
  <summary>**Click to see photo**</summary>
  
![IMG_20221003_042554_1](https://user-images.githubusercontent.com/57917164/193503377-a44d7bd7-b233-4564-8db1-2f3a98339751.jpg)
  
</details>

2. add monet theme for Android 12+

**Comment by meypod** [comment]
Hi
about the first suggestion; android already does swap those places, if the OS language direction is changed (for example if OS language is set to Arabic vs English). doing it so manually comes with a bit of complexity I'm not willing to implement right now.

about the second suggestion: I may add it some time later, but right now there's not much supported libraries that are stable for react native that I can use to build the UI. Supporting it would require some major changes which probably will change the look and structure of the UI. I may take an attempt at it later if you have any library in mind to use instead of native-base.  
I know about [this](https://github.com/Assembless/react-native-material-you) and [this](https://callstack.github.io/react-native-paper/introducing-v5-with-material-you.html) but they are in early stages.

thanks for your suggestions
