### ISSUE TITLE
How to contribute 

### ISSUE THREAD

**Issue by Mohmad-Naser-alnakeshbandi** [meypod/al-azan#12]
I would like to contribute in this project,  so developing the UI and adding some Features?

But how should we organise it?

**Comment by meypod** [comment]
well if the features are not related to adhan, like Qibla finder, I'm not willing to add to the project, I'd like to keep it a simple app solely for adhan

for each feature/change (including UI) you can create a separate issue and if we decided to add/change, a PR

about UI I'm really not sure, 
If you are a UI/UX designer, I'd like to see some images of the new Design before any change is done to the code, Because I don't want to get far from what information and how it currently gives. It is indeed opinionated because I'm It's first user after all. (I like the main screen's prayer times as is, but other screens like settings and intro can be improved a lot I think)
and notice that we are using [native-base](https://docs.nativebase.io/) right now, I'm not sure how drastic we can change the UI while using it.
