### ISSUE TITLE
New Prayer Times

### ISSUE THREAD

**Issue by ghost** [meypod/al-azan#141]
Asselamu aleykum,

i wanted to ask if it would be possible to add "Diyanet/Ditib" Prayer Times to the App? I know that the App already got "Diyanet Prayer Times from Turkey" but since I live in Germany, there are other Diyanet Prayer Times for us.

Here is a good Site for the Times:
https://www.gebetszeiten.de/

If you click on there and the City, you click on mwl 2007 in the top and then on Ditib/IGMG. Those are the Prayer Times we use. I hope you can add them in the App. Because it would make it a lot easier to use the App, then always looking it up online for the Prayer Times.

I really hope that it would be possible! Thanks!

**Comment by meypod** [comment]
Wa alaykum assalam

the app works offline and needs parameters to calculate the times
from the website you gave I tried to find the needed parameters and I only could find fajr angle and isha angle

but those aside, I am not actively developing the app right now as I'm busy, so I can't probably add it to the app any time soon, but you can use Custom method for calculation and enter the angles if you find them and it should work I think

overall from my experience Diyanet method has a lot of custom rules which they don't use themselves for the time calculation on the turkish version of it. I don't know if the website you mentioned applies them or not, but if they do, It wouldn't be possible for this app to calculate them because of the special rules that apply in different times/circumstances

**Comment by ghost** [comment]
Oh okay, I understand. Okay I will try in sha Allah.

Okay, good to know. Thank you. Yes, I don't know either. Okay, I understand what you mean. Thank you for the Informations and your help, shukran.
