### ISSUE TITLE
Accrescent?

### ISSUE THREAD

**Issue by ghost** [meypod/al-azan#145]
hey i would love to see the App on Accrescent Store (which is the most secure and private Store and better solution than Github) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

**Comment by meypod** [comment]
Hi
I consider f-droid a secure app store and GitHub is only for convenience.
I haven't heard of Accrescent store and it adds to maintenance burden, hence I'm not willing to publish on more stores

Thank you for taking time to suggest

**Comment by Jeffrey2307** [comment]
I understand that and np :)

**Comment by ghost** [comment]
F-Droid is claiming to be freedom and privacy, not security. F-Droid want to maximize device compatibility by not raising minimum SDK level for example.

https://privsec.dev/posts/android/f-droid-security-issues/

**Comment by meypod** [comment]
I have read it now and I disagree with a lot of the points

I have opted out of reproducible builds because I wanted them to sign the app, as I have done the same with google play, not that I could not create reproducible apks

They check the apks for viruses and unusual connections as well when you submit an apk

Overall it's not like every app gets included into f-droid easily, in fact they have pretty good filters

At the end, it's the users responsibility to have good security practices. Sure, things help, but up to a point anyway. There's (almost) nothing stopping you from downloading and installing a random malware on your device


-------------

F-droid stuff aside (thanks for the link), I have already mentioned my reason for not adding other stores,
It adds to the maintenance work

**Comment by ghost** [comment]
@meypod I don't share the same views in these topics but never mind. And no problem.
