### ISSUE TITLE
App size raises question

### ISSUE THREAD

**Issue by Noino** [meypod/al-azan#16]
How come this app which does only prayer times is >40MB blob, while similar apps like https://github.com/mirfatif/NoorUlHuda which also includes the Quran is only 3.3MB, and even the most bloated mainstream contender Muslim Pro (play store) manages with 30 and some MB?

Feels wrong.. What am i not seeing?

**Comment by meypod** [comment]
while I am not happy with the size myself, the reason is actually quite simple
first, it's a react native app, which comes with a LOT of libraries (itself, and third party ones that I had to install to use native functionality), which probably gives the app a head start in 20 mb or so, while the actual code for the app plus assets (images, etc) is only around 4-5 mb (extracted, much less when compressed),
the other reason is that the app is compiled for different architectures, each of them has their own set of compiled files, which bloats the apk size even further.
I invite you to extract the apk and check the size of each of folders inside `lib` folder for yourself

It feels wrong, but it doesn't mean It's malicious
I hope this has helped make it clear why the app size is large
while I would like to reduce it, without doing a pure native implementation, there's not much I can do about it
I'm planning to separate builds for each arch and enable proguard, which will help it reduce the size, but I don't know how much it will reduce (probably ~5-10% for proguard, 10-20% for separating the builds)
proguard without proper configuration breaks the app, thats why I was staying away so far

**Comment by meypod** [comment]
also note that NoorUlHuda downloads extra data after It's installed to provide the functionality, like `Quranic texts and translations, fonts and Adhan audio file` as it says in it's readme. while this apps does not *require* any extra downloads to do what it needs to do

**Comment by Noino** [comment]
But of course! I knew there had to be a common sense explanation.

Thank you for taking the time to lay it out on such a detailed level. 
I have to say I am impressed with the configurability and clarity of your app, as someone who doesn't read Arabic having a clean widget with English labels really helps me out a lot.

If only there was a feature/companion app for the Quran that was equally clean and easy to use * winkwink * (maybe out of scope but I'll make the feature request anyway :))

**Comment by meypod** [comment]
I'm glad you like the app
While I would like to do the Quran app/feature, I can't and probably won't any time soon, or maybe at all. But I like to see it happen as well :)

**Comment by meypod** [comment]
and I have good news
I tried splitting per arch (without pro-guard) and the app size will be around ~18 MB now
I'll release both the universal and per arch on GitHub from now on
I have to see how f-droid handles this to make this change

**Comment by meypod** [comment]
released splitted APKs in [v1.7.1](https://github.com/meypod/al-azan/releases/tag/v1.7.1)
working with f-droid to release the splitted APKs on there as well

**Comment by Tanzin01** [comment]
As'slam wlkm. 

What do you mean by "clean & easy" eaxactly? Kindly can you explain a bit/describe the theme idea? I ,may, can give it a try Ins'sha Allah  :)

**Comment by meypod** [comment]
just to be clear, I do not intend to add Quran or related features to this app, if I'm going to add, it will be in a separate app
PRs for anything not related to Adhan will not be accepted

**Comment by Noino** [comment]
Wa'alaykumu s-salam

Nicely done reducing the footprint.

By clean and easy I'm basically mainly comparing to Noor-UI-Huda. You've got a simple main page, obvious menu item, good menu structure, clean icons, descriptive titles and useful descriptions for options, whereas Noor I feel is much less clear, doesn't explain much of anything, some options are just simple icons, to enter the main menu you just have to know to tap the screen once to reveal the ... button, its just all over the place. The Quran portion is a struggle to use without being able to read Arabic, even if i can download a translation, the "go to" menu, titles & headlines are still illegible for me. 
Overall Noor takes some getting used to, gotta press things to find out what they do, where Al-Azan doesn't require experimentation.

I think Muslim Pro does the Quran part pretty well. Doesn't try to cram too much too tightly. Sadly that app has other major drawbacks.

Btw. on a side note, My phone tells me Al-Azan has stopped quite frequently, are there any accessible logs or something that could provide insight in to why?

**Comment by meypod** [comment]
Assalamu alaykum

before using the commands below, please check if your device has any battery optimization settings applied to the app, that is most likely the cause. you can check the battery optimization settings inside the app's settings menu, if everything was fine there, also check this website and check your brand: https://dontkillmyapp.com/

but if you believe there's something causing the app to crash, here is some commands you can use to check the logs for the app. you have to enable your device's USB debugging mode and have ADB installed (you can download this quite easily) to use the following commands:
```bash
# crash log: (this can contain info about other apps, you have to use grep like commands below if you want to filter the log)
adb logcat --buffer=crash
#  general logs of app:
adb shell "logcat -b all *:D  | grep -e 'com.github.meypod.al_azan'"
# related to notifee library, it can contain other apps logs if they also use it:
adb shell "logcat -b all *:D  | grep -e 'app.notifee.core'"
# react native's logs:
adb logcat *:S ReactNative:V ReactNativeJS:V
```
