### ISSUE TITLE
In widget show countdown until next prayer.

### ISSUE THREAD

**Issue by GibreelAbdullah** [meypod/al-azan#22]
For reference - See salatuk app widget.

![IMG_20230108_110443](https://user-images.githubusercontent.com/10581984/211182072-1be0bd33-4e0f-47ac-b44f-027238ad797d.jpg)

The timer can be shown as +00:30:00 if 30 minutes have passed since the start time of current prayer and -01:00:00 if 1 hour remains till the time of next prayer.

It should show time elapsed for current prayer for 30 min and then switch to the time remaining till the next prayer.

**Comment by meypod** [comment]
I wanted to add countdown to next prayer since the beginning, but the there was some limitations with react-native that I decided to not use it. Even current widget was a bit hard to create to begin with, as react native complicates things further
but I'll keep this open, I may come back to it after I have finished other planned features
I don't promise that I will add this but I may give it a go again

**Comment by meypod** [comment]
I could not think of a good reason for the behavior you described, and it would increase the complexity a lot
I have added a simple countdown to the next prayer in 1.12.0 with an option to enable it inside the widget options

I also added adaptive theme support for android 12+

1.12.0 will be released soon, you can [download the preview from github](https://github.com/meypod/al-azan/releases/tag/v1.12.0-rc2)
f-droid builds are delayed due to a problem with qibla finder update

**Comment by GibreelAbdullah** [comment]
Doesn't matter much. Jazakallahu Khairan for the update. It is now my default prayer times app.
Have you published it on play store?

**Comment by meypod** [comment]
Hi
I'm close to publishing it on google play store, I'm waiting till translators have double checked the translations.

**Comment by GibreelAbdullah** [comment]
Bro, it's almost Maghrib time here. The widget is still showing time till Sunrise.

![Uploading Screenshot_2023-03-13-18-15-33-540_com.saggitt.omega.png…]()

**Comment by meypod** [comment]
your screenshot is broken, can you please reupload the picture ?

**Comment by meypod** [comment]
and which version are you using ?
there was a bug before 1.12.0, please update  if you haven't yet

**Comment by GibreelAbdullah** [comment]
![Screenshot_2023-03-13-18-15-33-540_com saggitt omega](https://user-images.githubusercontent.com/10581984/224717377-c8603677-1101-4889-9f93-cd687540c001.png)

I'm using 1.12

**Comment by meypod** [comment]
that's definitely weird, I'll look into it

**Comment by meypod** [comment]
try [v1.12.2](https://github.com/meypod/al-azan/releases/tag/v1.12.2) and let me know if the issue came up again

**Comment by GibreelAbdullah** [comment]
Hey sorry, didn't see the messages. It was a weird one time issue. I didn't face that again even on the same version.
