### ISSUE TITLE
Audio output besides phone speakers

### ISSUE THREAD

**Issue by hpatel001** [meypod/al-azan#32]
As salamu 'Alaikum,

Thank you so much for building such a customizable app.

I wanted to setup the app to recite the Adhaan from an external speaker via the headphone jack as my phone doesn't go loud enough for the whole house to hear.

I looked into this and apparently by default android (I'm using 7.0) doesn't output 'alarm' audio through the headphone jack (probably not bluetooth too). There are some alarm apps that enable this however in their settings.

It would be really helpful if you could implement this. Additionally, this would be useful for students who want to have your app active while studying in a library or living in residence but only want the app to recite through headphones.

thank you

**Comment by meypod** [comment]
wa alaykum asalam

I'll try to add it in general settings in a future update
I think simply switching the playback mode to "music" can help with this issue

**Comment by meypod** [comment]
added this as a settings under `notification & sound` settings, will be available in 1.13.0 soon

**Comment by meypod** [comment]
just as a side note for my future self:
I tried to make it so that when this setting is enabled, only when headphones/speakers are detected the app will play on them using media volume, otherwise it will fallback to the old behavior of using "alarm" volume and settings.
this was to prevent unexpected behaviors.
