### ISSUE TITLE
The app does not play adhan

### ISSUE THREAD

**Issue by starlordabell1835** [meypod/al-azan#38]
Hello, I have had the app for sometime now and it worked flawlessly. It played adhan for the prayer times I specified. Lately, it's not playing adhan.

At the time of that prayer the app shows you the full-page adhan screen but then quickly exits without playing the adhan. It didn't happen before. 

Also when I try playing a different adhan under **Settings > Muezzin > [adhan name]**, I get the track could not be played error message.

I have reset app data. I have battery optimization set to off. What am I missing or is this a bug?

Thank you

**Comment by meypod** [comment]
Hi
yes this is a bug
however, I need to know which version of the app you are using, this may be already fixed.
you can see what version you are using from about page in settings

**Comment by meypod** [comment]
Latest version is 1.13.1 right now, f-droid updates are behind the github releases
The bug is probably fixed in the latest version
You can find it here: https://github.com/meypod/al-azan/releases/tag/v1.13.1
However to try it you have to remove the app and install from here
But uninstalling and reinstalling will probably fix it on the version you are on anyway
You can wait for f droid or install from github now
Please let me know of your result

**Comment by starlordabell1835** [comment]
Appreciate your response. I just downloaded the latest `universal` apk and installed it. Will let you know of the result in the next 24 hrs.

**Comment by starlordabell1835** [comment]
Works as expected
