### ISSUE TITLE
Summer clock problem

### ISSUE THREAD

**Issue by RZHSSNZDH** [meypod/al-azan#47]
Salam
**Describe the bug**
In iran every year we had summer clock, but from this year we will not use summer clock. So our clock is same as last fall and winter's clock, but al-azan app shows azan times 1 hour later than true times because it uses summer clock. I do not know the problem is because of which library.

**Expected behavior**
For example it should show fajr in 5 am, but shows in 6 am.

**Device Info :**
 - Device: Galaxy J7
 - OS: lineageOS 17.1

**Comment by meypod** [comment]
Va alaykum assalam

please tell me which version of the app are you using?

also, what did your phone do, did it automatically adjust time or your time stayed the same ?
because if your phone did advance the time, then you manually changed it back, the time zone of your phone will be still in effect, which will cause the time's calculated in the app be as if you didn't change the time (so you will see wrong times)

if your phone did not change the time automatically, the app calculates the correct time

if your phone is showing the correct clock without any manual settings, but the app is calculating incorrect times, then it is a bug

otherwise, you can do two things:
1. if you have root access, you can edit your android's timezone files and update your country's timezone
2. you can adjust the times in the app using the adjustment settings (but since not all prayer times have adjustment, I may have to look into it)
