### ISSUE TITLE
Add Hijri date adjustment. listing famous islamic occasions in calendars.

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#60]
Al salmo Alekom wa rahmato Allah wa barakatoh.
Eid mobarak
Can you list famous islamic occasions in the calendar.
For example:
9 dou al hija is (day of aarafah)
10 dou al hija is (Eid Al Adha)
...ETC
________________
Also I have noticed something with the app, When I select "Show countdown?" , nothing happens. I don't know if this is a bug or not.

Thank you.

**Comment by TorCzaf** [comment]
Also can you please add an option to modify Today's date?

**Comment by meypod** [comment]
Wa alaykum assalam wa rahmato Allah wa barakatoh

Special events are not added because they are determined by moonsighting and app's calendar is pre-calculated, so it may be inaccurate

Show countdown is for widgets (Notification widget and Home screen widget)

Manually adjusting Hijri dates is planned
Gregorian date is adjusted from phone settings, So I don't think I will add it

**Comment by TorCzaf** [comment]
Okay.

Can you please make an option to show countdown in the main screen of the app too?

Also I suggest making "Show countdown" option in "Widget settings" disabled and not to be enabled unless the user enables first "Show notification widget", because It is confusing to enable Show countdown option without enabling Show notification widget.
I mean I see "Show countdown" option only appears to be working when I enable   "Show notification widget".

**Comment by meypod** [comment]
I'm not sure about adding it to the main screen of the app, But I will think about it. I plan to redo the UI in near future, I'll see if I can fit it on the screen somehow or not, because the home screen does not have enough space for adding things without cluttering it

Show countdown option cannot be disabled because you can have a home screen widget at any point in time.

> I mean I see "Show countdown" option only appears to be working when I enable "Show notification widget".

try adding the app's widget on your home screen

**Comment by meypod** [comment]
this is the home screen widget that I'm talking about:
<img width="150"  src="https://raw.githubusercontent.com/meypod/al-azan/main/fastlane/metadata/android/en-US/images/phoneScreenshots/9-homescreen-widget-light.png"/>

**Comment by TorCzaf** [comment]
I did  it. Thank you.
Okay can you add an option to change the hours to A.M and P.M  system?
For example instead of 23:00 it is 11:00 P.M,  in case people prefer this system.

**Comment by TorCzaf** [comment]
Also I have a question why when I change location to another country for example to  USA (I am not in USA by the way) and choose ISNA method -because USA uses ISNA- I get different prayer times than those on Google.

**Comment by meypod** [comment]
> Okay can you add an option to change the hours to A.M and P.M system?
For example instead of 23:00 it is 11:00 P.M, in case some people prefer this system.

there is already an option in display settings

> Also I have a question why when I change location to another country for example to USA (I am not in USA by the way) and choose ISNA method -because USA uses ISNA- I get different prayer times than those on Google for USA.

there can be several reasons. send the website you are checking and the exact location you are comparing so we can check
but overall know that there's more settings than Location+Method to determine the time
you can see these settings under Advanced settings in calculation settings

**Comment by TorCzaf** [comment]
Here are the screenshots, 

**Note in the first two images that there is big difference in hours while there is no difference in minutes between Google and the app.**

![Screenshot_20230630-215332_Google](https://github.com/meypod/al-azan/assets/137301636/0e5c421e-439c-4898-bcf4-bf36bad4a818)

![Screenshot_20230630-214215_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/08bb1413-6326-4523-a43c-244479fffe8f)


**And these are my settings in the app**
![Screenshot_20230630-214306_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/26ee4b15-ebf7-4f54-b985-e33c970f2890)

![Screenshot_20230630-214330_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/0a41ccf8-9513-4cae-a358-72ba5b918deb)

![Screenshot_20230630-214322_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/43e613a5-f0da-4478-abbb-d3dd73c725ef)

**Comment by TorCzaf** [comment]
**Same problem with Afghanistan, and maybe other countries too but here there is difference in hours and minutes**
https://timesprayer.com/en/prayer-times-in-kabul.html

![Screenshot_20230701-030405_Mull](https://github.com/meypod/al-azan/assets/137301636/04c5cce1-3d63-42d7-8bf9-6eda56b4c7f3)


![Screenshot_20230701-025201_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/f024ff69-2f91-43b1-9907-11c85855d4d9)

**These are the settings**
![Screenshot_20230701-025318_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/9157d711-0dcc-48c2-82ee-df7810a59d6b)

![Screenshot_20230701-030047_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/b882f7f7-5607-4ed4-ac51-b223a4aafcac)

![Screenshot_20230701-030130_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/1c05c8ff-19a9-4add-ae13-bbd31d39b568)

**Comment by meypod** [comment]
I See ... 

Don't forget you have to set your phone's timezone to those countries as well
the times are probably correct, just shown in your current time zone :)

**Comment by TorCzaf** [comment]
Yes I was thinking about phone's timezone but I wasn't sure.
Thanks for confirming.
It would be good to type that somewhere in the app so people don't misunderstand.

**Comment by meypod** [comment]
I'll keep this open till I add hijri date adjustment

**Comment by TorCzaf** [comment]
OK :)

**Comment by AI-IMED** [comment]
Ohh, I will have to make the application in (Stand by) mode and use my alternative application until the option to edit the Hijri date is available, because today we have the first of Muharram while in the application is the second of the month, I like your application very much and I hope to add the option to edit the date as soon as possible.

**Comment by meypod** [comment]
@AI-IMED please test the release candidate from github releases, I have added hijri date adjustment

**Comment by AI-IMED** [comment]
I performed a clean installation of the application and without importing a backup copy, I found that when making a modification to the Hijri date, the modification includes the name of the day as well!, this should not happen at all.

![٢٠٢٣٠٨٠٢-١١١٠٠١](https://github.com/meypod/al-azan/assets/38974362/b4ba4f20-a3f3-4ef1-be5c-945eb3d687ee)

**Comment by programer00112** [comment]
> You are right But the only solution to this is to remove the day from hijri date below and in widget I'll fix it soon

AsSalaamu 'Alaikum wa Rahmatu Allaahi wa Barakaatuhu,
Another solution would be to look at the week day from the gregorian calendar and convert it directly into the Arabic week day name (Friday --> جمعة) without using adhan-js, while still getting the rest of the information from adhan-js.

**Comment by meypod** [comment]
date formatting does not come from adhan-js
adhan-js only handles adhan calculation
