### ISSUE TITLE
[Bug] Midnight and Tahajjud Highlight

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#67]
Hi When it is 12:00 AM (The new day) Midnight becomes unhighlighted and also Tahajjud never becomes highlighted...
Not even "Highlight current prayer" works for them.

**Comment by meypod** [comment]
Hi
in app , or in widget ?
app automatically advances to next day at 12:00 AM on widget, so you probably wont ever see tahajjud being highlighted
app also advances to next day at 12:00 AM inside the home screen, but It's so subtle you may not notice it. when it happens, make sure you check the day before, usually it Is indeed highlighting, just not in the way you expect it to happen

**Comment by meypod** [comment]
I mean when clock goes past 12:00, home screen automatically advances to the next day, so to see the tahajjud time, you have to go back one day again

**Comment by meypod** [comment]
I mean keep an eye on the date of the home screen, after 12:00 AM the date updates to the new day, so the times also change to the new day
each day has it's own prayer times, which can extend beyond 12:00 AM, but all of the times are shown for the date that is shown at the top

so if midnight or tahajjud are after 12:00 AM, and you are opening app and looking at the times, you see the times for the new date (today)
to see midnight and tahajjud that are after 12:00 AM, since they are for the previous day, you have to go look at the previous day's times
