### ISSUE TITLE
Add Countdown and widget settings for reminders

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#69]
Hi , can you please add a button to show countdown for reminders somewhere in the app?

Plus can you also make another "widget settings" section for reminders ?

So at the end, user would have one widget for prayers and one for reminders both would show on phone at same time.

If you don't prefer to put some widget settings for reminders, then at least put countdown option for reminders if possible please.

Thank You.

**Comment by meypod** [comment]
Hi
What's the point of showing countdown for reminders ?

**Comment by meypod** [comment]
Notification panel shows upcoming reminder notification 1 hour before reminder

**Comment by meypod** [comment]
Also I'm going to make the upcoming notification time customizable, so that can actually help you prepare if you need it 5 minutes before the alarm instead of 1 hour

**Comment by meypod** [comment]
Another dedicated online calendar app that grabs data from different sources of moon sighting would be better for reminding of events
But that is out of scope for Al-Azan, and someone else needs to create such an app

and offline calendar apps exist, but they also may be inaccurate due to being pre-calculated:
https://github.com/persian-calendar/persian-calendar

**Comment by meypod** [comment]
What's the point of reminding people that an event is upcoming but don't show them the time
that would confuse people
People will look for calendar, and most people don't notice it's inaccurate, so they will look at the app and use the dates as is

rather, there are apps dedicated to being calendar, people can use those apps
and you may notice it later, but I already have provided such notification but only for beginning and end of Ramadan, because I know majority of people will simply forget or not know at all
