### ISSUE TITLE
Helping translation of program and sound

### ISSUE THREAD

**Issue by Serince** [meypod/al-azan#7]
I couldn't find the project in the translation.io to help tranlate to Turkish. Is there any way to choose phone message sounds as notification sound?

**Comment by meypod** [comment]
Hi
translation.io is invitation only
if you want to help I can invite you, but right now due to not having comments/context details for translation keys, you would have to look at the code to figure out which translation is used where which makes it a bit harder to translate

for notification sounds, I believe It's a OS thing, so you would have to go to the application settings -> notifications, there in the bottom you would find 3 channels for notifications, one for `Reminder`, one for `Upcoming adhan`, and one for the `Adhan` itself. you can change notification sounds there

**Comment by Serince** [comment]
For translation, I can do my best. You can send an invitation.

**Comment by meypod** [comment]
I sent you an invitation

**Comment by Serince** [comment]
Thank you! I got the invitation and translated all :)

**Comment by meypod** [comment]
Can you translate the key I added just now ? It's the text shown for when selecting the Turkish language in the dropdown

**Comment by Serince** [comment]
I have edited :)

**Comment by meypod** [comment]
It's available in [v1.2.0](https://github.com/meypod/al-azan/releases/tag/v1.2.0) now. thanks for contributing

But It will probably be a ongoing thing, because I will be adding new features here and there and those will need translations as well
I would be happy if you would translate new entries whenever It's needed

**Comment by muava12** [comment]
Hey, i want to translate to Indonesian if you not don't mind

**Comment by meypod** [comment]
@Serince please translate the new entry

**Comment by meypod** [comment]
no need anymore, I'll auto translate the trivial stuff, I'm sure everyone is busy 
I'll try to only ping you when needed
I'll enable auto translate for all new languages, if the new translations were not correct, please fix them, I'll release the fixes on the next release
