### ISSUE TITLE
Add an independent automatic time system for chosen location 

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#71]
Hi I know that I have already suggested to type somewhere in the app that phone time zone affects prayer times, but how about if you put a time system for your app that depends on the chosen country?
For example if user chooses Afghanistan and chooses its right calculation method, app should automatically switch to Afghanistan time instead of users modifying their phones time zone
Or you can put time zone options in the app so user can choose from.

My idea is that your app shouldn't depend on phone time zone settings because some people are lazy to adjust their phones' improperly adjusted settings or some people such as young children or old people...etc don't have knowledge on how to do that and they may depend on highly inaccurate prayer times.
And there may be other reasons (which I don't know) to not depend on phone's settings.

**Comment by meypod** [comment]
I don't agree, because the time you see is the time that adhan happens, in your current timezone, in that specific coordinates

even if the times look crazy, they are correct
they are for that specific coordinates
so for example if you are in USA and select Afghanistan and some method, it is actually giving you the time that the adhan is happening at that coordinate, it may be 2 am for you but it is not in Afghanistan

I can't agree because I think the time you see in other time zone would be irrelevant to you in any way.

the only use case I can think for this feature is for when testing the methods and locations and comparing them to their official docs
on the downside it increases the complexity of time handling which I don't want to bring into the app

**Comment by meypod** [comment]
Also it is very unlikely that someone have incorrect time zone, because it is usually set to automatic and provided by the cellular network

**Comment by meypod** [comment]
> You mean like adhan happens in Afghanistan when time in USA is 2am for example?

Yes

> So if I chose any time zone in phone and chose any country in the app...app would do adhan in the same time that adhan happens in the chosen country?

as far as I understand, yes
the time zone is just a representation of the actual time that it's going to happen.
it doesn't matter in what time zone you are, as long as the method and coordinates are correct, the adhan would happen at it's correct time
at least that's what's supposed to happen, if there isn't any weird bug anywhere ... :)

**Comment by meypod** [comment]
so , for example, if you are in USA and choose some method for usa and set your coordinates to usa, but change your timezone to whatever you like, the adhan that was going to happen at 12:30 PM would still happen at 12:30 PM, you would just see it as 1:00 AM for example

**Comment by meypod** [comment]
You're welcome :)
