### ISSUE TITLE
Add 99 names of Allah and zakat calculator and maybe Azkar

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#77]
Hi , Can you please add 99 names of Allah in the app I took this idea from five prayers app, also add zakat calculator in app If possible please, of course there are lots of them but I believe "All-in-one" is great concept. For example this app, has zakat calculator and I think it has "Azkar" maybe hisn Al muslim and in same time has prayer times 
https://github.com/choubari/Muslim-App
And from what is written I think it is built in "Java".

And as I said before :) it is rare to find islamic apps that care for privacy and in same time are open source...
For example the app I mentioned above has ads
(According to Google play).

**Comment by meypod** [comment]
Hi

while all-in-ones can be good, it can become hard to maintain and opinion-free.

Al-Azan is not a full featured Islamic app, nor aims to be one.  I try to keep Al-Azan strictly about "adhan",
while I have added Qada counter and Qibla map, I did so because I had many discussions about it being tightly related to prayer
but other than those two I probably won't add any feature that is not directly related to adhan and it's calculation
