### ISSUE TITLE
Ones and tens digits bug in "Custom" option for reminders

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#92]
Hi When I use "Custom" option for reminders to put numbers that look similar to number options in the app in terms of ones and tens digits, the app forces me to use the number options.

For example:
If I put 100 mins it becomes 10 min because the app has 10 min option but if I make it like 110 it remains on 110 because the app doesn't have 11 min option 

Another example if I put 150 mins it becomes 15 min but if I put 160 it remains on 160
And so on....

**Comment by meypod** [comment]
Hi
Thanks for testing the app and finding this
I have applied the fix, will release it in the next version

**Comment by meypod** [comment]
this is because the input has to finish editing before it changes the value behind the scenes (the keyboard must close)

this is a bit tricky to do, because if I check as user types in the number, it can turn into the default view when it becomes "10" for example. if I wait till user finish, user may never finish editing and instead press confirm before closing keyboard.

have to think about it more

**Comment by meypod** [comment]
I have fixed this
will release with next version
