### ISSUE TITLE
Compass Warning, Countdown, UI, Widget Colors, Custom Parameters Notes, New options

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#93]
Assalamu Alaykom 
I have got 8 ideas 

**1#I realized that your Compass Warning doesn't have much details** 
![Screenshot_20230909-064844_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/04e0a713-e2f3-42e3-b9e5-43881bf3f6f3) 

So how about you add more details like that? This can make people more careful
![Screenshot_20230909-063805](https://github.com/meypod/al-azan/assets/137301636/500bcc2a-59da-4418-9eaf-c5bcc96277fe)
App name: "Salam App" 

Now 2,3,4,5 are from "Prayer Times (Namaz Vakti)"
https://github.com/metinkale38/prayer-times-android unfortunately it is built in kotlin I guess 

**2#Makrouh or Forbidden prayer times Indicator** 
But I think we need to read some fatwas first 
![Screenshot_20230909-070659_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/265ce977-b822-4f18-8a9f-42e6e97293ae) 

**3#Widget - countdown Minutes settings**
This could be useful to hide seconds in widget 
![Screenshot_20230909-072641_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/6db14225-6ebb-401b-8d6c-d95cb557c722) 

**4#Notification-widget colors (Black-Gray-White),** you can also add these colors for screen Widget too. I understand you don't plan to add themes/colors but can you add these 3 colors at least please? Useful for those who put bright or dark backgrounds on their screen and want to distinct widget's color. 

![Screenshot_20230909-073038_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/59e9c919-f54b-4338-bfce-f04a506aadcc) 

Widget in white color
![Screenshot_20230909-074555_Gallery](https://github.com/meypod/al-azan/assets/137301636/e6882abd-4dde-43d9-925a-c3a87362d5ca) 

**5#"Show mintues in Notification-icon"**
I think that is a small countdown for the next prayer,  and I think it is a good idea to have it at the top.
![Screenshot_20230909-082516_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/dc1036e2-1954-49cf-90d8-43ee0c64b0de) 

**6#Add notes box for custom method** for those who do their research regarding angles/parameters and high latitudes for specifc regions and want to remember what they discovered. 

**7#Add an option that allows to put an audio that should be automatically played directly after adhan** this could be useful for those who want to put dua after adhan or put something that motivates them to go to Mosquee or pray early...ETC, also useful for those who want only to put specific audio that is separated from adhan. 

**8#Can you add countdown in main screen of the app please?** 

you have said before that you will see if you can fit it on the screen somehow or not and you plan to redo app UI due to the cluttering. 

I see some space down at the bottom 
![Screenshot_20230909-104557_Al-Azan](https://github.com/meypod/al-azan/assets/137301636/42901d20-0732-4ed5-acd7-1712603e7198) 

Or how about you redo the UI of your app to look similar to that in "Salam App"
![Screenshot_20230909-105713](https://github.com/meypod/al-azan/assets/137301636/0fa9cc6b-af46-4e81-a1b5-fb6785ed075d)
Their UI even still has some space.
____
And Thank you.

**Comment by meypod** [comment]
Hi, thanks for taking your time to write this

1# I'll add a note for magnetic items nearby
2# not planned
3# android does not allow removing seconds from chronometer widget. and implementing a custom timer would be consuming more battery, because then the app has to send the updates to the widget constantly (every minute vs only at prayer times).
4# not planned due to complexities involved in theming widgets correctly on different android versions
5# for the same reason as 3# its not efficient
6# I'm not willing to add this as I see little benefit from doing so. you can always take notes through other means and not just for specific parts of UI like methods.
7# not planned. you can use reminder with custom timing to achieve such behavior with some delay. you can also use a custom adhan with audio attached at the end.
8# I'll try to add it when I redo the UI

**Comment by meypod** [comment]
> I got another idea, can you add a setting that allows user to disable reminders for some time and then they should be enabled automatically?
Because sometimes I turn off reminders for long periods and forget to turn them on

Can you explain what's your exact use case ? because this feature does not seem like something that someone would use regularly

> What do you think of "1/7 of the night, median"?

I don't know what it is

**Comment by meypod** [comment]
I thought about it, and it seems the best way to implement such feature, is to create a screen where you can see the adhan/reminders for the next 24/48 hours, and then allow user to enable/disable them there. But it's very complex to implement, as alarms are not scheduled all at once before hand. so I don't think I will be implementing this

though the other way of doing this, which seems to be a lot easier, is to use the scheduled DND feature of android. you can say for examples on Mondays from 12:00 to 14:00 enable DND.
on some Samsung devices such feature is even more granular, you can say which apps can bypass DND (https://www.xda-developers.com/how-to-create-custom-modes-and-routines-on-a-samsung-device/)
even without scheduled DND, the manual DND mode is probably what you should be using when you want to temporarily stop your phone from making any noise

You may have the global bypass DND enabled, in that case you have to wait until I implement the per adhan/reminder DND bypass setting. in that case the issue with using DND will be solved.

> Also I realized that when the reminder plays and I come to turn it off, sometimes alarm screen doesn't appear thus I can't turn the reminder off using volume buttons unless I unlock the screen first. I don't know why this happens.

what is your phone ? can you tell me the model and brand ? please always create separate issues so we can track them individually. this style of multiple feature/bug per issue is not really good for tracking progress of each.

> When I make a reminder to wake up for Fajr or maybe something else but sometimes I am awake before the reminder plays and in same time I have people with me, so I disable the reminder...and this happens a lot with me. I disable the reminder because sometimes I am awake and don't want to wake other people up.

well if you are awake and you know it is going to play, it's very easy, as app sends an upcoming alarm notification which you can use to cancel the alarm. why you disable the reminder instead of using that?
