### ISSUE TITLE
Enabling reminders automatically after period of time determined by user

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#94]
**This is a separated issue from #93 so we don't take #93 further away from its main ideas and make it a complex issue. (Sorry for my grammar).**
_____
Can you add a setting that allows user to disable reminders for some time and then they should be enabled automatically?
Because sometimes I turn off reminders for long periods and forget to turn them on, 

for example the user should be able to disable reminder by putting custom time 

Also the period during which the reminder is Disabled must be written somewhere for example like "Disabled for 2 hours and 30 mintues"...ETC 

>Can you explain what's your exact use case ? because this feature does not seem like something that someone would use regularly 

For example if I go to gym or do swimming everyday or attend a meeting or go to important places where there are people, and my phone is in somewhere else (like in the safe), I may keep reminders disabled for the time I need to be done with my things or business so people don't get annoyed as my reminder sound is strong and kind of annoying. And I have several reminders. 

Another example, If I live with a roommate who sleeps at any time (sleeps irregularly) and hates alarms during his sleep period, then I may need this feature. 

All of these examples might lead me to forget to enable reminders by myself as someone who uses several reminders, which is why this feature is needed. 

Another reason for the need for this feature and this is the most important one...
When I make a reminder to wake up for Fajr or maybe something else but sometimes I am awake before the reminder plays and in same time I have people with me, so I disable the reminder...and this happens a lot with me. I disable the reminder because sometimes I am awake and don't want to wake other people up. 

Also I realized that when the reminder plays and I come to turn it off, sometimes alarm screen doesn't appear thus I can't turn the reminder off using volume buttons unless I unlock the screen first. I don't know why this happens. 

>I thought about it, and it seems the best way to implement such feature, is to create a screen where you can see the adhan/reminders for the next 24/48 hours, and then allow user to enable/disable them there. But it's very complex to implement, as alarms are not scheduled all at once before hand. so I don't think I will be implementing this 

>though the other way of doing this, which seems to be a lot easier, is to use the scheduled DND feature of android. you can say for examples on Mondays from 12:00 to 14:00 enable DND.
on some Samsung devices such feature is even more granular, you can say which apps can bypass DND (https://www.xda-developers.com/how-to-create-custom-modes-and-routines-on-a-samsung-device/)
even without scheduled DND, the manual DND mode is probably what you should be using when you want to temporarily stop your phone from making any noise 

>You may have enabled the global bypass DND in Al-Azan, in that case you have to wait until I implement the per adhan/reminder DND bypass setting. in that case the issue with using DND will be solved. 

>well if you are awake and you know it is going to play, it's very easy, as app sends an upcoming alarm notification which you can use to cancel the alarm. why you disable the reminder instead of using that? 

>what is your phone ? can you tell me the model and brand ?

**Comment by meypod** [comment]
> For example if I go to gym or do swimming everyday or attend a meeting or go to important places where there are people, and my phone is in somewhere else (like in the safe)

all cases you mention are actually a use case of DND. it makes your phone don't make a noise while you are busy/not around.

> Do you mean I can use scheduled DND with "the per adhan/reminder DND bypass setting"?

I mean when I add "per adhan/reminder dnd bypass" feature to the app, it will probably cover all use cases

> Here are my DND settings by the way

yeah the `Schedule` part of the settings is what I'm talking about

> -Not all people use Samsung's phones some people use oppo that use Android OS and other manufacturers that use Android OS version, I meet people who use oppo and xiaomi...not everyone buys Samsung phones, I guess it is because that they are expensive...in poor countries people may buy less expensive phones from other manufacturers.

I am pretty sure [DND was added around android 5.0 (api 21)](https://developer.android.com/develop/ui/views/notifications#dnd-mode), and you can only install Al-Azan on Android 7.0+

> -It is a little bit annoying to add and remove exceptions in DND settings because DND can affect everything.

and from pictures from link above about DND, it seems nearly all phones support configuring DND in a way that you don't miss important calls/messages while DND is on. I mean the point of DND is to make phone make least noise possible. this is what you want when you put it in a safe or you go into a meeting.

> -Not all Samsung phones are the same I mean not all phones have the same or all of DND settings and I don't know whether or not all Samsung phones including the old ones have scheduled DND.
-Not all people understand how to use Samsung's DND settings especially simple people they only click on DND button and that is all.

using scheduled DND is very convenient when you have a fixed routine, but not necessary. everyone can enable DND manually when they don't want their phone to make noise for some period and then turn it off when they are done.

and I just checked android 7.0 on emulator, and it supports scheduled DND, and since DND was added in android 5.0, I think most manufacturers have this feature already

> I think sometimes it is better to build your own settings instead of depending on a manufacturer's modified Android OS version

this is true sometimes, more in past, but old devices are getting replaced more often than before and most people have newer phones, even if it's cheap, it usually comes with a newer android version that has these features built in
I think this is putting time on reinventing the wheel

> Well, at least it is not impossible..right?

yes, not impossible. 
but it seems even less valuable when such functionality is provided at OS level, for all apps. so leveraging that seems like a better option.

> Anyways, it is all up to you. And I hope for your app the best.

thank you

> I sent the information to you privately.

Thanks. It seems that app behavior is inconsistent about alarm screen on Samsung devices. I still have not figured out why and logs don't seem to point to any issue. maybe this is a bug in [the library I use](https://github.com/invertase/notifee) for notifications. 
It would help a lot if you could notice under which conditions your phone does not show the alarm screen. is it always happening at a particular time? was silent mode or DND active before? was app in recent apps? if you ever found out what may cause it, please let me know

> Oh you mean that "Cancel" button?

Yeah

> I thought this was to remove the notification, how about you change it to "Cancel Alarm"? Because this looks confusing when you put "Cancel" only.

I see, I will change it

> I got 4 more suggestions for you, do you want me to make 1 issue for each of them or 1 issue per 2 suggestions?

the best way is to create 1 issue per suggestion/bug. I know it sounds a bit of work but that way the title is shorter and easier to search for me and other people.

**Comment by meypod** [comment]
Closing this since this will be resolved by adding the bypass settings to reminders/adhans from #80
