### ISSUE TITLE
Hijri Date Format in English or Device's language

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#95]
I see your app has "Numbering system" and the app has 3 types of Hijri date format but can you also add another type that follows the device's language? Or that is in English?
Because not all people understand Persian or Arabic language.

![Screenshot_20230916-004827_Gallery](https://github.com/meypod/al-azan/assets/137301636/ab48ceac-4840-47f9-9a94-9abf38247e14)

**Comment by meypod** [comment]
The default of app is to be like the option you have drawn a circle around. with one exception, and that's Hijri calendar. Hijri calendar will always be Eastern Arabic unless forced by choosing a numbering system.
if users want to force a particular numbering system, they can choose one, otherwise it will be determined by language by default.

**Comment by meypod** [comment]
> with one exception, and that's Hijri calendar. Hijri calendar will always be Eastern Arabic unless forced by choosing a numbering system.

so the only place the default is not following system language is hijri calendar

**Comment by meypod** [comment]
added a new option that will allow you to either use selected language, or Arabic for the lunar calendar

will release with next version
