### ISSUE TITLE
Add Lock Notifications and Auto Clear Notifications settings

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#99]
Hi, Can you add settings to "Lock Notifications" (This is good especially for Upcoming alarm notifications) and add "Auto Clear Notifications after specified time" settings?
![Screenshot_20230924-060628_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/9fa10eec-cb2d-4bea-b715-67fc1f7e4c88)

**Comment by meypod** [comment]
Hi
Android is limiting ways of "Locking" notification with each new version, so going forward this is useless, especially for upcoming prayer, because locking requires certain conditions in newer versions that upcoming alarm notification does not satisfy. 
also if you accidentally dismissed the upcoming alarm notification, simply re open the app and it will be sent in a few seconds again (unless you press cancel alarm, which in that case it will not show up again).

Auto Clear Notification is really unnecessary in my opinion, as dismissing notifications literally takes 1 or 2 seconds, and there's a clear button provided by OS which also helps clearing notifications as well
